app = "task-nest"
primary_region = "lax"
console_command = "/code/manage.py shell"

[build]

[deploy]
release_command = "python manage.py migrate --noinput"

[env]
PORT = "8000"
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "task_manager.settings"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[mounts]
source = "vol_remdepex2636k7d4"
destination = "/code/media"

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1

[[statics]]
guest_path = "/code/staticfiles"
url_prefix = "/static/"