app = "task-nest"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
DJANGO_SETTINGS_MODULE = "task_manager.settings"
DEBUG = "False"

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gunicorn", "python"]

[deploy]
release_command = "python manage.py migrate"

[[services]]
http_checks = []
internal_port = 8000
processes = ["app"]
protocol = "tcp"
script_checks = []

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443