# Generated by Django 5.1.7 on 2025-03-12 14:14

from django.db import migrations


def add_initial_data(apps, schema_editor):
    Category = apps.get_model("tasks", "Category")
    Category.objects.create(name="Work")
    Category.objects.create(name="Personal")
    Category.objects.create(name="Urgent")


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_assignee_alter_task_category_and_more"),
    ]

    operations = [migrations.RunPython(add_initial_data)]
