# Generated by Django 5.1.7 on 2025-03-13 00:21

from django.db import migrations, models


def update_statuses(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(status="todo").update(status="open")
    Task.objects.filter(status="done").update(status="closed")


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_initial_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("reopened", "Reopened"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]

    operations = [migrations.RunPython(update_statuses)]
